import {addTranslations, setName} from "./src/tree.js"

addTranslations({
    score: "очки",
    lives: "жизни",
    level: "уровень",
    bullets: "пули",
    shipLayer: "частиКорабля",
    asteroids: "астероиды",
    bonuses: "бонусы",
    explosions: "взрывы",
    startingLives: "стартовыеЖизни",
    ship: "корабль",
    acceleration: "ускорение",
    deceleration: "замедление",
    accelerationLimit: "пределУскорения",
    angularSpeed: "скоростьПоворота",
    weapon: "оружие",
    state: "состояние",
    alive: "живой",
    dead: "мёртвый",
    gameOver: "играОкончена",
    invulnerable: "неуязвимый",
    asteroidType: "типАстероида",
    flame: "пламя",
    asteroid: "астероид",
    explosion: "взрыв",
    death: "смерть",
    extraLife: "дополнительнаяЖизнь",
    newLevel: "новыйУровень",
    music: "музыка",
    bonus: "бонус",
    currentWeapon: "текущееОружие",
})
