import {addTranslations} from "./tree.js"

addTranslations({
    true: "да",
    false: "нет",
    null: "пусто",

    Object: "Объект",
    Array: "Массив",
    Key: "Клавиша",
    Image: "Изображение",
    Sprite: "Спрайт",
    ImageArray: "МассивИзображений",
    Layer: "Слой",
    Canvas: "Холст",
    Area: "Площадь",
    Shape: "Форма",
    Label: "Надпись",
    Constraint: "Связь",
    LinearChange: "ЛинейноеИзменение",
    Move: "Переместить",
    Animate: "Анимировать",
    SetBounds: "УстановитьГраницы",
    LoopArea: "ЗациклитьПлощадь",
    ExecuteActions: "ВыполнитьДействия",
    RotateImage: "ВращатьИзображение",
    Delayed: "Отложенный",
    DelayedRemove: "УбратьПозже",
    AddAction: "ДобавитьДействие",

    texture: "текстура",
    sound: "звук",
    layer: "слой",
    sprite: "спрайт",
    key: "клавиша",
    path: "путь",
    size: "размер",
    width: "ширина",
    height: "высота",
    xMul: "множX",
    yMul: "множY",
    widthMul: "множШирины",
    heightMul: "множВысоты",
    visible: "видим",
    columns: "столбцы",
    rows: "ряды",
    centerX: "xЦентра",
    centerY: "yЦентра",
    halfWidth: "полуШирина",
    halfHeight: "полуВысота",
    image: "изображение",
    images: "изображения",
    imageAngle: "уголИзображения",
    angle: "угол",
    speed: "скорость",
    animationSpeed: "скоростьАнимации",
    active: "активен",
    actions: "действия",
    parameters: "параметры",
    cooldown: "охлаждение",
    time: "время",
})