export let project = {
    texture: {},
    locale: "ru",
    locales: {},
    _object: {},
    key: {},
    scene: [],
    actions: [],
    registry: {},
    modules: [],
    _data: "",
    loadTextures: () => {},
    init: () => {},
    update: () => {},
}